### PR TITLE
Raise update

### PR DESCRIPTION
**Pull request by celiasmith**
Reorganization of the site and some rewriting of content to be more product/service focussed.

### CODE REVIEW

**Comment by tbekolay** [comment]
I pushed a commit with a revamped projects page (which is now the research page), and used that same template for the products and services pages. LMK if you want some changes on that; in the meanwhile, I still have the following on my todo list:

- [x] make some white image backgrounds transparent
- [x] ensure tabs look ok on smaller screens
- [x] switch nengo image for new logo
- [x] 3 column layout for press awards
- [x] move about us stuff to footer
- [x] products, services, research headers (the `<h2>` tag) on index look weird, should probably be either way bigger or totally out of the way ?

**Comment by celiasmith** [comment]
I like the new tabs. Might look better if there were little circles on the tab images?

**Comment by tbekolay** [comment]
I can try it yep, was also thinking maybe rounded rectangle?

**Comment by celiasmith** [comment]
kinda like the circles as a site theme... at least see if it looks ok?

**Review by tbekolay — APPROVED** [review]
I finished all the items on my todo list. @celiasmith didn't like the links in the footer, while I didn't like the dropdowns in the navbar, so we compromised with at combined "About us" page that has the old team, contact, culture, and partnership pages all merged into one super page.

With all these changes, I'm happy with the newly reorganized and restyled site! I can merge on @celiasmith's OK, or we can wait for another review if people want to look at this before we move forward.

**Comment by celiasmith** [comment]
yup looks good to me; i'd be good to just mrege

**Comment by tbekolay** [comment]
Sounds good, I'll clean up the history then merge.

**Pull request merged**
