### PR TITLE
Add paper presentation and talk to BrainBoard page

### PR DESCRIPTION
**Pull request by bmorcos**
Decided maybe we should add the paper talk and presentation to the website too.

I just pointed to the presentation and talk hosted on github (unless we want to move these anywhere else).

### CODE REVIEW

**Review by krisfrenette — COMMENTED** [review]
Is there a way that we can add more context / content surrounding this? It feels a little like an after thought?

**Comment by bmorcos** [comment]
I can try and rework it a little

**Comment by bmorcos** [comment]
How does this look to you now?

**Comment by krisfrenette** [comment]
LGTM!

**Pull request merged**
